server {
    listen 80;
    server_name localhost *.localhost;

    root /usr/share/nginx/html;
    index index.html;

    charset utf-8;
    client_max_body_size 20M;

    # API Requests -> Laravel 11 Backend (PHP-FPM)
    location /api {
        fastcgi_pass backend:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/backend/public/index.php;
        include fastcgi_params;
    }

    # Frontend React SPA Routing
    location / {
        try_files $uri $uri/ /index.html;
    }
}
