import React, { useEffect, useRef, useState } from "react";
import { AlertCircle, Image, Loader2, Trash2, Upload } from "lucide-react";
import type { StoreAssetUpload } from "../../adapters/uiAdapters";
import { uiErrorMessage } from "../../contracts/uiError";
import type { StoreConfig } from "../../types";

interface Props { config: StoreConfig; activeTenantId: string | null; mediaOwnerKey: string | null; onChange: (key: keyof StoreConfig, value: unknown) => void; uploadAsset: (tenantId: string, file: File, signal?: AbortSignal) => Promise<StoreAssetUpload>; }
const input = "w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-sky-500";

export default function MerchantStoreContentEditor({ config, activeTenantId, mediaOwnerKey, onChange, uploadAsset }: Props) {
  const [uploading, setUploading] = useState(false); const [error, setError] = useState<string | null>(null);
  const generation = useRef(0); const controller = useRef<AbortController | null>(null); const context = useRef({ activeTenantId, mediaOwnerKey }); context.current = { activeTenantId, mediaOwnerKey };
  const set = <Key extends keyof StoreConfig>(key: Key, value: StoreConfig[Key]) => onChange(key, value);
  useEffect(() => { generation.current += 1; controller.current?.abort(); controller.current = null; setUploading(false); setError(null); return () => controller.current?.abort(); }, [activeTenantId, mediaOwnerKey, config.aboutImage]);
  const upload = async (file: File | undefined, element: HTMLInputElement) => { element.value = ""; if (!file) return; if (!activeTenantId || !mediaOwnerKey) { setError("رفع الصور من الجهاز متاح بعد إنشاء المتجر واعتماده."); return; } if (!['image/jpeg','image/png','image/webp'].includes(file.type) || file.size <= 0 || file.size > 5 * 1024 * 1024) { setError("استخدم JPEG أو PNG أو WebP بحجم لا يتجاوز 5 ميجابايت."); return; } controller.current?.abort(); const task = new AbortController(); controller.current = task; const id = ++generation.current; const tenant = activeTenantId; const owner = mediaOwnerKey; setUploading(true); setError(null); try { const asset = await uploadAsset(tenant, file, task.signal); if (task.signal.aborted || id !== generation.current || context.current.activeTenantId !== tenant || context.current.mediaOwnerKey !== owner) return; set("aboutImage", asset.url); } catch (reason) { if (!task.signal.aborted && id === generation.current) setError(uiErrorMessage(reason, "تعذر رفع صورة النبذة.")); } finally { if (id === generation.current) { controller.current = null; setUploading(false); } } };

  return <div className="space-y-5" dir="rtl"><header className="rounded-2xl bg-gradient-to-l from-sky-950 to-slate-900 p-5 text-white"><h3 className="text-base font-black">المحتوى والتواصل</h3><p className="mt-1 text-xs leading-6 text-sky-100">حرر نبذة المتجر ووسائل التواصل الحقيقية. لا توجد استمارة رسائل أو وعود استجابة وهمية.</p></header>
    {error && <div role="alert" className="flex gap-2 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs font-bold text-rose-700"><AlertCircle className="h-4 w-4" />{error}</div>}
    <section className="space-y-3 rounded-2xl border border-slate-200 bg-white p-4"><h4 className="text-sm font-black">نبذة عن المتجر</h4><input className={input} value={config.aboutTitle ?? ""} onChange={(e) => set("aboutTitle", e.target.value)} placeholder="عنوان النبذة" /><textarea className={input} rows={5} value={config.aboutText ?? ""} onChange={(e) => set("aboutText", e.target.value)} placeholder="قصة المتجر" /><textarea className={input} rows={3} value={config.aboutVision ?? ""} onChange={(e) => set("aboutVision", e.target.value)} placeholder="رؤية المتجر" />
      <div className="rounded-xl border border-slate-200 bg-slate-50 p-3"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black">صورة النبذة</p><p className="text-[11px] text-slate-500">رابط HTTPS أو أصل مُدار للمتجر القائم.</p></div><div className="flex h-16 w-20 items-center justify-center overflow-hidden rounded-lg bg-white">{config.aboutImage && !/^(data|blob):/i.test(config.aboutImage) ? <img src={config.aboutImage} alt="" className="h-full w-full object-cover" /> : <Image className="h-5 w-5 text-slate-300" />}</div></div><input dir="ltr" className={`${input} mt-3`} value={/^(data|blob):/i.test(config.aboutImage ?? "") ? "" : config.aboutImage ?? ""} onChange={(e) => set("aboutImage", e.target.value)} placeholder="https://example.com/about.jpg" /><div className="mt-2 flex gap-2"><label className={`relative inline-flex items-center gap-1 rounded-xl px-3 py-2 text-xs font-black ${activeTenantId && !uploading ? "cursor-pointer bg-slate-900 text-white" : "cursor-not-allowed bg-slate-200 text-slate-500"}`}>{uploading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Upload className="h-4 w-4" />} {uploading ? "جارٍ الرفع" : "رفع من الجهاز"}<input className="absolute inset-0 opacity-0" type="file" accept="image/jpeg,image/png,image/webp" disabled={!activeTenantId || uploading} onChange={(e) => void upload(e.target.files?.[0], e.currentTarget)} /></label>{config.aboutImage && <button type="button" onClick={() => set("aboutImage", "")} className="inline-flex items-center gap-1 rounded-xl border border-rose-200 px-3 py-2 text-xs font-black text-rose-700"><Trash2 className="h-4 w-4" /> إزالة</button>}</div></div>
    </section>
    <section className="space-y-3 rounded-2xl border border-slate-200 bg-white p-4"><h4 className="text-sm font-black">وجهات التواصل</h4><p className="text-[11px] leading-5 text-slate-500">اترك أي حقل فارغًا لإخفائه. أرقام WhatsApp الدولية تبدأ بـ + ورمز الدولة.</p><div className="grid gap-3 sm:grid-cols-2"><input dir="ltr" className={input} value={config.phone ?? ""} onChange={(e) => set("phone", e.target.value)} placeholder="الهاتف الدولي +967..." /><input dir="ltr" className={input} value={config.whatsapp ?? ""} onChange={(e) => set("whatsapp", e.target.value)} placeholder="WhatsApp +967..." /><input dir="ltr" type="email" className={input} value={config.email ?? ""} onChange={(e) => set("email", e.target.value)} placeholder="البريد الإلكتروني" /><input className={input} value={config.address ?? ""} onChange={(e) => set("address", e.target.value)} placeholder="العنوان الفعلي" /><input className={input} value={config.workingHours ?? ""} onChange={(e) => set("workingHours", e.target.value)} placeholder="ساعات العمل" /></div></section>
    <section className="space-y-3 rounded-2xl border border-slate-200 bg-white p-4"><h4 className="text-sm font-black">حسابات التواصل</h4><div className="grid gap-3 sm:grid-cols-2">{([['instagram','Instagram'],['twitter','X / Twitter'],['tiktok','TikTok'],['snapchat','Snapchat']] as const).map(([key,label]) => <input key={key} className={input} value={config[key] ?? ""} onChange={(e) => set(key, e.target.value)} placeholder={label} />)}</div></section>
  </div>;
}
